### ISSUE TITLE
True Pomodoro

### ISSUE THREAD

**Issue by HighPriest** [Medvedev91/timeto.me#18]
I am a user addicted to GoodTime pomodoro timer, but because it lacks the goals feature, I have decided to checkout your work.

The visualizations are really nice and deserve applause, you have really good eye for UI design.

But, the application, in its current state, where end of a task automatically starts the task again, isn't really a pomodoro timer.

What GoodTime does much better, is that each task uses the same, predefined time of 20 minutes, followed by a 5 minute break.
If you want more time, you can just swipe on the timer up & down to add minutes (the swiping adds value to each minute changed). This, makes it easy to start the timer.
What is really important, is the persistent "are you still paying attention@" alarm when timer has ran out and no new task has been chosen. Disabling an alarm by interacting with the app, makes it actually rewarding to set a goal.

So, what would you say about:
- Setting a predefined Timer Hint to all the categories.
- Creating a separate "Break" category.
- When the timer runs into break, play constant alarm with notification asking to "continue task" or "start break". Each setting should set the timer to predefined value. Break sets the category to break.
- When timer runs out of break, play the same "are you there" alarm. If user selects "go back to work", start the timer with previously selected category.
- Make categories second class citizens. First focus on just starting the timer and then letting the user customize what they want to monitor. No one really needs to set the timer for a few seconds on some task (you set the timer in minute increments anyway), so maybe don't save the category / session when changing the category, but when the timer finishes the session, or is set into break by the user.

**Comment by appstome** [comment]
Thank you for such a detailed feedback.

I totally agree that the current pomodoro is not perfect. I will definitely make some improvements, but it's not as simple as it may seem.

The conceptual problem is that specialized apps can do deep customization, but in this app, pomodoro is kind of a side-effect.

Another point is that we are all different, we have different lifestyles and work processes, what works for you may not work for others.

I'm trying to make pomodoro as versatile as possible working out of the box.

> where end of a task automatically starts the task again

This is not starting a new task, but continuing the current task until you start a new one.

> predefined time of 20 minutes

I plan to make "timer prompts". They will always be displayed on the home screen to immediately start a specified activity with the specified timer.

> If you want more time

You can tap on the timer to display the preset hints.

> is the persistent "are you still paying attention@" alarm

> play constant alarm with notification

In my experience, trying to make notifications more intense just make it a habit to ignore them.

> Setting a predefined Timer Hint to all the categories.

All activities are different, so you can set different settings for each one.

> Creating a separate "Break" category.

> start the timer with previously selected category

> No one really needs to set the timer for a few seconds on some task 

It makes sense, but I think it's overkill. I believe that the app should serve us, not us to the app. You don't need to start a timer for second tasks. It's okay if the past task is active. I mean, we're trying to get more things done, not report to the app.

Anyway, when I improve pomodoro, I will keep your suggestions in mind.

**Comment by Medvedev91** [comment]
Since 2024.05.15.529, it is possible to set break time for each activity or disable it.

**Comment by Medvedev91** [comment]
Since 2024.07.08.560 the Pomodoro was completely remade. Including separate "Break" category, new UX, setting "Until Time", simple addition of time, etc.

Related discussion https://github.com/Medvedev91/timeto.me/discussions/59

More information in the in-app readme.
