### ISSUE TITLE
Tap position is shifted on fire HD 10.

### ISSUE THREAD

**Issue by BunBunHello** [Medvedev91/timeto.me#35]
dear sir.
I am sorry for my poor writing, but I would appreciate your help.
Recently, I have been using your software with an application called F-droid.
However, when I do so, the tap position of your application is misaligned.
I tried to solve this problem with a Google search and found a blog. [link:](https://zenn.dev/tomoya0x00/articles/e9c0558e5d8e16)
It seems that we can use what looks like the code of the programming language introduced in this blog.
If you don't mind, I would appreciate it if you could correct the relevant part of the code using the above blog as a reference.
Best regards.

Translated with DeepL.com (free version)

similar issues [link](https://github.com/mihonapp/mihon/issues/70)
                         [link](https://github.com/mihonapp/mihon/issues/547)

**Comment by Medvedev91** [comment]
It will be difficult to fix because I don't have a Fire HD device. But I hope it will be fixed after updating the UI engine used in the app.

**Comment by Medvedev91** [comment]
After some research, I think it should be fixed on the Fire HD side.
