### ISSUE TITLE
[feature suggestion] Maximum goals

### ISSUE THREAD

**Issue by ClaymeCall** [Medvedev91/timeto.me#42]
Hello ! I use the app to increase my productivity, but also to decrease my  procrastination. I have a task "Loose Time" allowing me to track how much I do exactly that.

I would like to set threshold goals I have to stay under to complete : as opposed to the "x minutes of sports minimum a week",
It could be "1h of lost time max /day" type goals. They could be visualized by a bar that depletes.

**Comment by ClaymeCall** [comment]
Currently, the goal feature is a target to attain, starting from 0. The bar is filled and counted as attained when you have spent enough time in a task. This works for tasks you want to maximize

My idea is that the opposite would be great for tasks I want to minimize. The bar would deplete rather than fill up, and the goal would be counted as attained if I still have time left at the end of the goals period.

**Comment by Medvedev91** [comment]
I believe the current goal feature solves your request. The only things to do is the customizable emoji and showing extra time.

**Comment by Medvedev91** [comment]
> I believe the current goal feature solves your request.

I mean you can consider the bar a limit, how much is left and how much has passed is already there. In fact, that's all you need. I don't see the point in complicating it.

**Comment by ClaymeCall** [comment]
Yes, changing the emoji and showing how much time has spilled would also work !

**Comment by Medvedev91** [comment]
> Yes, changing the emoji and showing how much time has spilled would also work !

Added to the backlog.

**Comment by opipoy** [comment]
Can it be also possible to limit the activity so when the time is up you cannot use it?

**Comment by Medvedev91** [comment]
> Can it be also possible to limit the activity so when the time is up you cannot use it?

It is an interesting but tricky thing. What if you started and then the limit came?

**Comment by opipoy** [comment]
> What if you started and then the limit came?

I agree that it can be a problem for when you start using the app.
so mabe insted of just saying that you cant do that it will pop up a warning that the limit has reached and if it was a mistake how to swich it off in the setting and then allow you to procced, or like let you only activate for only five mins.
Could that work? Or i did not understand the problem?

**Comment by Medvedev91** [comment]
Goals already indicate if the limit has reached. I think if we ignore this indication, in real life we will ignore other warnings as well.

**Comment by opipoy** [comment]
But at least it eould make it more apperant that the limit has been exceeded

**Comment by Medvedev91** [comment]
> Yes, changing the emoji and showing how much time has spilled would also work !

Done https://github.com/Medvedev91/timeto.me/releases/tag/v2024.11.17.569
