### ISSUE TITLE
[question] Immersion vs Pomodoro.

### ISSUE THREAD

**Issue by ConEstArthur** [Medvedev91/timeto.me#52]
Hi Dev
I had some questions on fundamentals to using the app.
How do you approach this scenario -
Say you need longer period of time to complete a certain task (under work category) than it was assigned to. Now the timer is overdue. How would you use the pomodoro now ? 
Would you start it for say 10 mins under the same "Work" Category ? 
But then Pomodoro would have its own pomodoro :) Provided you already have set up 10 mins pomodoro timer for your work related tasks.
Or
Would you start it under "Other" category ?
But here we found we have parted ways with how app calculates pomodoro. It by its default behavior records the break timer under the main category itself.

Circling back to the our main intent for using the app - We want to get things done. 
I wanted to draw your attention to what I think is the **main concern** here. 

## **Task** **vs** **Time** 
I categorize my tasks into two approach - Time based (for tasks you already know should not take longer than its assigned time) and Task based (when you prefer quality more I think ?)
Now what this app traditionally does better than other productivity apps is how it does not let you waste time. It requires me to set a timer again so that I do not deviate from getting essential things done.

I think we can make pomodoro approach better for things where we prioritize quality. We can do more to retain that immersion.
I had few crude suggestions but I think what you would eventually implement later would be a much finer solution.
- A DND toggle for tasks or categories.
- To curb the pomodoro problem we can at the end of an ovedue session, show a "Finish this session" or something like that. Tapping on that would start the pomodoro :)
- I don't know if this makes sense or not or people would call us freaks after this - What if after the pomodoro session it already starts "other" timer. So the "other" category is basically your wasted time. But here's the thing If I pause a timer - It starts the timer under "other" category already. So I do not know whether "other" category should be my "errands" or "wasted time" category.

This post is a deviation from my other posts here. It's not cultivated by any means. I'm trying to figure out things as I progress.
Let me know your insights to my approach to getting things done. It would help me a lot.

Thanks again for your hard work. Cherishing the new Calendar Template feature. :)

**Comment by Medvedev91** [comment]
Your points are what I've been thinking about for the past few months. The main challenge is there are so many life scenarios that the app should fit.


# Timer and Pomodoro

We tend to think of pomodoro as a strict timer, such as 45/5. For me personally, it doesn't work at all. It even makes it worse, notifications distract from the deep work. 

The way that fits me best is a timer WITHOUT notifications. For me, timer is a great thing to indicate if I lost control of my time. For example, I see that the timer is 10 min overdue - that's okay (sometimes the task takes a bit longer), but 30 minutes means I have to stop and figure out what's going on.

I call it “flexible” pomodoro, I alternate between work and breaks, but the way I feel, the timer serves as an indicator.

### Solution:

Pomodoro is already optional. Making notifications optional cover two ways: strict and flexible pomodoro.


# Pause -> Continue -> Pause ->…

We decided to use pomodoro (strict or flexible). Now we have to decide HOW to do that.

### Solution:

1. Make the pause button customisable: setting the timer and activity on pressed.
2. If the timer is overdue, pressing pause will save the paused task with the initial timer. So, after a break, the timer can be restarted with a single touch.

For example, “Work 45 min” is overdue, tapping pause starts the “Rest” activity for 10 min and save paused task “Work 45 min” on the home screen.

This way we:
- Don’t have to choose timer/activity every time;
- Keep the task name between breaks;
- Do everything from the home screen with a single touch.


# Starting the Timer

We decided how to pause -> continue.., but how to start the timer?

I often start a timer like work for 45 min. Pressing the timer icon and selecting the right activity each time is annoying.

Another case: I open tasks, realise there are no tasks to do, pressing the timer icon to start task form tasks list… annoying.

### Solution:

Adding custom buttons with the activity/timer set to the home and tasks screens.

---

What do you think of the solutions I proposed? Will they work for you?

**Comment by Medvedev91** [comment]
Also, I've openned github discussions, feel free to use.

**Comment by ConEstArthur** [comment]
Excellent suggestions.
Yes they would work.

Here are few things I'd like to add to them.

## Pause button during an activity

### Suggestion A

we can use short press or long press for starting an activity. Because let's not forget if we are proposing that starting an activity again and again from the menu could be annoying; it'd be more annoying when you have to do something urgently and you're met with that menu. 

So in this scenario action for short press can be configured . You can set it to any acitivity with timer that you prefer.
Long Press could pop up menu to start custom activity and timer.

--- 
### Suggestion B

We could introduce a new avenue to starting a timer. We can implement **Suggestions**. 
It uses something like **Favourites** + **Recent** + **Most used** model for it.

It may work for homescreen as well as for window where you have to choose an activity and a timer.
Imagine apart from list of your activities. It could show **suggestion** to you to quickly set up a timer.

**Favourites** - we could pin our favourites combo (activity+timer)
**Recent** - This would work for this scenario too
> We decided how to pause -> continue.., but how to start the timer?

**Most Used** - Self-explanatory.

By using this we could even eliminate long press and short press suggested previously.
It gets rid of the need to edit tasks frequently. 
Pause button would pop up this window. You don't select an activity and additionally a timer for it. You just tap on your pinned or most used combo and voila.


## Overdue timer

When a timer is overdue say **Work 45 min**. We are at 55 mins now. 
We would only interact with app when our work is done, right ?
Maybe then **pause** could turn into a tomato :) 
And it would start a pomodoro timer.

Because it would not make sense to keep it a pause button I surmise ? 
We could always start a new task from the homescreen (enhanced by suggestion B and simlarly your approach of **custom buttons**)

Home screen could based on **suggestion** something like **hop back in**. So you could start your recent activity (overdue timer) again. This also encompasses your Pause--> continue--> Pause approach.

Thanks :)
---

How's your arm ?

**Comment by Medvedev91** [comment]
> We would only interact with app when our work is done, right ?

Everyone works in different ways. I can only tell about my experience.

I interact with the app not only when the task is done. I aim to work for 45 minutes. If I see that I am working more than 60 minutes, I force myself to take a break. Otherwise, I lose my productivity.

> Maybe then pause could turn into a tomato :)

Right now, for me, it's exactly how it works. I use the pause button as a timer for a break.

---

So, there are a million ideas on how to change the app. I think the best way is to create custom buttons first. It doesn't look like a wrong decision. Then test how it works and plan further.

---

> How's your arm ?

I'm fine. Thank you!

I can't type a lot, so I'm polishing the UI and working on the readme.

**Comment by ConEstArthur** [comment]
> Everyone works in different ways. I can only tell about my experience.

It was poor choice of words from my side. I meant suggestions or custom buttons would tell you to start the same activity again after that 60 mins session.
If I let the timer run its course, it would count pomodoro time under the same activity I guess? 
If I choose pause for pomodoro it counts it under "Other". So that was my concern.

**Comment by Medvedev91** [comment]
I've found a way that works well for me. I'am about to implement this, but before I do, I want to ask your opinion.

1. I have this, regular overdue:

![Simulator Screenshot - iPhone 15 Pro - 2024-06-16 at 22 45 51](https://github.com/Medvedev91/timetome/assets/100848382/d38dacb1-d38b-4fe9-b1f9-cffcd3c2f720)

2. Then I tap pause or timer and get this:

![Simulator Screenshot - iPhone 15 Pro - 2024-06-16 at 22 46 10](https://github.com/Medvedev91/timetome/assets/100848382/d332dacc-9a81-4f65-9c11-9fb335fb2e82)

3. Tap the play button or timer again get this:

![Simulator Screenshot - iPhone 15 Pro - 2024-06-16 at 22 46 51](https://github.com/Medvedev91/timetome/assets/100848382/3e9d22d2-2027-4216-bda1-beac54ac5311)

---

Under the hood the "Pause" button creates a paused task and starts the "Break" activity. "Play" button restarts the paused task.

It means you only you need one tap before the break and one tap after the break. As a pleasant side effect we have separated time tracking for breaks.

**Comment by ConEstArthur** [comment]
Phenomenal!
This solves everything 😭

**Comment by Medvedev91** [comment]
Please check it out https://github.com/Medvedev91/timetome/discussions/59

**Comment by ConEstArthur** [comment]
> Please check it out #59

Will do sir. Thanks ☺️

**Comment by Medvedev91** [comment]
Due to the latest release, can we say the issue is solved?

**Comment by ConEstArthur** [comment]
> Due to the latest release, can we say the issue is solved?

Yes, you can mark it as solved.

**Comment by Medvedev91** [comment]
Okay, actually, this issue is what pushed me to remake the pomodoro.

**Comment by ConEstArthur** [comment]
> Okay, actually, this issue is what pushed me to remake the pomodoro.

And you did an excellent job at it.

Thanks a lot for your hard work. 😃
