### ISSUE TITLE
Feature suggestion, option to show app time usage in others.  

### ISSUE THREAD

**Issue by AverageOpenSourceEnjoyer** [Medvedev91/timeto.me#57]
**Summary;**
Gym: 2h
Office/Work: 9h
Cooking: 1h 30 minute

**[App Usage]**
YouTube : 2h 10 minute
Music: 1h 3 minute

Gmail: 17 Minute

other:9h

**Also, option to add app to task, so time spent in app related to task get included in that app automatically in task hour:**

For example: Gmail app time get included in work time.

**Comment by Medvedev91** [comment]
Why not use a dedicated app for this?

**Comment by AverageOpenSourceEnjoyer** [comment]
Been using this very app for time tracking and all, this app is good and have everything else as per my need, so thought this feature might be great idea, any app recommendation for this app companion or replacement?

**Comment by AverageOpenSourceEnjoyer** [comment]
App time with task integration is what this suggestion is about.

**Comment by Medvedev91** [comment]
Okay, after a bit of research, I decided to drop this idea. I don't understand what unique functionality I can come up with. There are OS-based solutions that work much better than I can provide.

Also, when we say "yes" to one feature, we are saying "no" to another. I am limited in time to work on this project, so I prefer to work on the more desirable features.

:(

**Comment by AverageOpenSourceEnjoyer** [comment]
@Medvedev91 I appreciate your suggestion. I have substituted some functions with the help of similar applications. Although it's not perfect, it has enabled progress. Your efforts are highly appreciated.

:)

**Comment by thiswillbeyourgithub** [comment]
Semi related but it might be of interest to some here. Home assistant companion app allows broadcasting the last used android app. I'm sure it  contains valuable code for anyone interested in implementing this. 

Heres the link: https://github.com/home-assistant/android
