### ISSUE TITLE
UI suggestion: tooltip on long press on UI elements

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [Medvedev91/timeto.me#63]
Hi,

I have to say I'me somewhat inconvinced by some UI aspects of this app. I think it could be solved if long pressing on any UI element could display a short explainer / tooltip.

For example, the Pause button has a vertically stretched aspect ratio (to my eyes at least) and it took me 2 days to figure it out. Long pressing on it could display "pause button" and make it clear.

Great app otherwise!

**Comment by thiswillbeyourgithub** [comment]
Addendum: I have yet to understand what notes are for!

**Comment by Medvedev91** [comment]
>  I think it could be solved if long pressing on any UI element could display a short explainer / tooltip.

I've created a readme for this.

I suggest creating github discussions for things that are not clear instead issues. I'll add this to the readme.

> Addendum: I have yet to understand what notes are for!

I use it to keep simple data, like wifi passwords.
