### ISSUE TITLE
FR: adding a limit on cirtain activity

### ISSUE THREAD

**Issue by opipoy** [Medvedev91/timeto.me#67]
I have been using the app for a while and its wonderfull, ive been using it as a way to track my time and try and limit my bad habits, i think it will be easier for me that the app would automaticly block me when a ceirtain time is met and will restart when the day is done

**Comment by Medvedev91** [comment]
Why not use goals? This is a solution for tracking bad habits as well.

**Comment by Medvedev91** [comment]
Please follow the #42
