### ISSUE TITLE
(question) What is Notes for? 

### ISSUE THREAD

**Issue by callit** [Medvedev91/timeto.me#70]
I'm assuming it's just it's own little notepad within the app, or a feature that will be added on to in the future. 

I don't see it mentioned anywhere in the documentation (except in one screenshot) and I don't see any way to link a note to a timer session or task or anything like that. The settings screen is an odd place for a notepad though, and since it's close to the checklists config, I thought it might have a similar function. 

I'm curious because it would be really nice to have a note attached to a timer session in some cases (which I believe is already a feature request elsewhere.)

I just want to know if there's some cool function I'm missing with Notes 😁

**Comment by thiswillbeyourgithub** [comment]
Answered there : https://github.com/Medvedev91/timeto.me/issues/63

**Comment by callit** [comment]
Ooof, don't know how I missed #68 haha - thanks for the feedback!

For those who are search challenged like I apparently am: 

From #63 :
> I use it to keep simple data, like wifi passwords.

From #68
>  the "note" feature has nothing to do with timetracking and is just to store text data, and is not related to any activity in particular or any other menu right?

> Yes, that's right. Someday I'll add this to the readme.

---
So basically just a place to store some text without leaving the app. Got it, thanks!
