### ISSUE TITLE
[feature suggestion] let timer be set by choosing an end time (possibly with an alarm)

### ISSUE THREAD

**Issue by avh4** [Medvedev91/timeto.me#71]
Let's say I have a meeting at 3pm.  I want to start my next activity or task with a timer that ends at 2:55pm so that I can go to my meeting on time.  When choosing how long to set the timer for, it would be nice to have an option to choose an ending time instead of choosing how many minutes to run for.  When setting timers this way, imo it would also be nice to have this make an alarm with different notification settings than the normal "timer ended" notification because then I wouldn't also have to set an alarm in my Clock app.  Also when setting timers this way, it'd probably be best not to remember this timer length for the "by history" timer hints.

**Comment by Medvedev91** [comment]
Under the "i" button you can tap on the time end and set the "Until Time".

**Comment by avh4** [comment]
Ah thank you!
