### ISSUE TITLE
Remove DependencyInfoBlock

### ISSUE THREAD

**Issue by licaon-kter** [Medvedev91/timeto.me#84]
ref: https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8403862907

We find that there is a `DependencyInfoBlock` in your APK.

It's a [Signing block](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) added by AGP and encrypted with the Google public key so it can't be read by anyone else except Google. You can read more about it [here](https://gitlab.com/fdroid/admin/-/issues/367) and [here](https://gitlab.com/fdroid/fdroidserver/-/issues/1056).

While this was added a while ago, we were only enforcing it for new apps, and recently we started scanning updates too.

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Thanks!

**Comment by Medvedev91** [comment]
Like this? https://github.com/Medvedev91/timeto.me/blob/6d67648849a09eef53b9a56eed819dfd2a94f6d2/android_app/build.gradle.kts#L45

**Comment by licaon-kter** [comment]
yup

**Comment by Medvedev91** [comment]
Ready https://github.com/Medvedev91/timeto.me/releases/tag/v2024.11.17.570

**Comment by licaon-kter** [comment]
thanks https://gitlab.com/fdroid/fdroiddata/-/commit/e5f2438ee6677bb8438338f1379b67c12e6e5649
